spring:
  profiles:
    active: dev
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  tomcat:
    accesslog:
      enabled: true
      directory: C:/log/scsstcss/yml
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: scsstcss_access
      suffix: .log
    basedir: C:/log/scsstcss/tomcat
